defmodule Storybook.UI.PixQR do
  use PhoenixStorybook.Story, :component

  def function, do: &RolezinhoWeb.Components.UI.PixQR.pix_qr/1

  def template do
    """
    <div class="rounded-cta bg-surface p-3.5 max-w-[358px]" psb-code-hidden>
      <.psb-variation/>
    </div>
    """
  end

  # Generated by our own code from a sample key, with no user-supplied fragment —
  # which is what makes it safe for the component to render with raw/1.
  defp sample_svg do
    Rolezinho.Pix.qr_svg("+5591984933238",
      name: "MARCIA",
      city: "BELEM",
      amount_cents: 1500,
      width: 176
    )
  end

  def variations do
    [
      %Variation{
        id: :with_caption,
        description:
          "Exists because copying a key fails often in person. The app never confirms the " <>
            "payment: the QR only carries the payee's data into the bank app. Printed on " <>
            "qr-paper so it stays scannable in the dark theme.",
        attributes: %{
          svg: sample_svg(),
          caption: "Pagando de outro celular? Escaneie o QR."
        }
      },
      %Variation{
        id: :bare,
        description: "Just the code, when the surrounding screen already explains it.",
        attributes: %{svg: sample_svg()}
      }
    ]
  end
end
