defmodule RolezinhoWeb.Components.UI.PixQR do
  @moduledoc """
  The event's Pix QR code, printed on white paper with a caption.

  Exists because copying a key fails often in person — a wrong paste, a key read
  aloud across a court. The app never confirms the payment: the QR only carries
  the payee's data into the bank app, and marking it paid stays a declaration by
  whoever paid.

  The code always sits on `qr-paper` (white in both themes): scanners need dark
  modules on a light field, and a QR drawn on the dark card cannot be read.

  The SVG comes from `Rolezinho.Pix.qr_svg/2`, generated by our own code with no
  user-supplied fragment, which is what makes it safe to render with `raw/1`.
  """
  use Phoenix.Component

  import Phoenix.HTML, only: [raw: 1]

  @doc """
  Renders the QR block.

  ## Examples

      <.pix_qr svg={@qr_svg} caption="Escaneie com o app do banco." />
  """
  attr :svg, :string, required: true, doc: "SVG markup from Rolezinho.Pix.qr_svg/2"
  attr :caption, :string, default: nil
  attr :class, :any, default: nil

  def pix_qr(assigns) do
    ~H"""
    <figure class={["flex flex-col items-center", @class]}>
      <div
        role="img"
        aria-label="QR code do Pix"
        class="size-44 rounded-row border border-hairline bg-qr-paper p-3 [&>svg]:size-full"
      >
        {raw(@svg)}
      </div>
      <figcaption :if={@caption} class="mt-2 text-center text-[13px] text-muted">
        {@caption}
      </figcaption>
    </figure>
    """
  end
end
